image: docker/compose:1.25.0-rc2

stages:
  - deploy

variables:
  MAIN_URL: cnynl.net
  LETSENCRYPT_EMAIL: clubdeninosyninasdenl@gmail.com

.variables_master: &my_variables
  stage: deploy
  tags:
    - cnynl.net
  only:
    - master

deploy:
  <<: *my_variables
  environment:
    name: master
    on_stop: stop
    url: https://${VIRTUAL_HOST}
  script:
    - docker-compose pull
    - docker-compose build
    - docker-compose up -d --force-recreate --remove-orphans
    - docker cp vhost.d/. nginx:/etc/nginx/vhost.d
    - docker cp htpasswd/. nginx:/etc/nginx/htpasswd
  variables:
    VIRTUAL_HOST: portainer.${MAIN_URL}
  when: always

stop:
  <<: *my_variables
  environment:
    action: stop
    name: master
  script:
    - docker-compose down
  when: manual
