version: "3.7"

services:
  # nginX Proxy
  nginx: 
    image: "jwilder/nginx-proxy:latest"
    container_name: "reverse-proxy"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
        - default
    ports:
        - "80:80"
        - "443:443"

  # nginX Config Generator
  # custom image with the following Dockerfile
  # TLS 1.3 support
  nginx-gen: 
    build: .
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    networks: 
        - default

  # nginX LetsEncrypt SSL
  nginx-letsencrypt: 
    container_name: nginx-letsencrypt
    depends_on:
      - nginx
      - nginx-gen
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx
    networks: 
        - default

  
   portainer_ce:
    container_name: portainer_ce
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
    - 8000:8000
    - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - portainer:/data

# External docker network (run only once)
# docker network create -d bridge nginx-proxy
networks:
  default:
    external:
      name: npm

volumes:
  certs:
  html:
  vhost:
  dhparam:
  portainer: