version: "3.7"

services:
  # nginX Proxy
  nginx: 
    image: "jwilder/nginx-proxy:latest"
    container_name: "reverse-proxy"
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /run/docker.sock:/tmp/docker.sock:ro
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    networks: 
        - default

  # nginX Config Generator
  # custom image with the following Dockerfile
  # TLS 1.3 support
  nginx-gen: 
    build: .
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    networks: 
      - default

  # nginX LetsEncrypt SSL
  letsencrypt: 
    depends_on:
      - nginx
      - nginx-gen
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    environment:
      NGINX_PROXY_CONTAINER: nginx
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: always
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - /run/docker.sock:/var/run/docker.sock:ro
    networks: 
      - default

  portainer_ce:
    container_name: portainer_ce
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
    - 8000:8000
    - 9000:9000
    command: -H unix:///var/run/docker.sock
    environment:
      VIRTUAL_HOST: portainer.${DOMAIN}
      LETSENCRYPT_HOST: portainer.${DOMAIN}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - portainer:/data
  
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.${DOMAIN}



# External docker network (run only once)
# docker network create -d bridge nginx-proxy
networks:
  default:
    external:
      name: npm

volumes:
  certs:
  html:
  vhost:
  dhparam:
  portainer: